[theme]
primaryColor = "#2563EB"             # Royal Blue
backgroundColor = "#FFFFFF"          # Murni Putih
secondaryBackgroundColor = "#F1F5F9" # Light Grey/Slate (Sidebar)
textColor = "#0F172A"                # Dark Text
