[theme]
primaryColor = "#38BDF8"             # Sky Blue (Tombol & Tab Aktif)
backgroundColor = "#0F172A"          # Dark Slate (Konten Utama)
secondaryBackgroundColor = "#1E293B" # Medium Slate (Sidebar & Card)
textColor = "#F8FAFC"                # White Smoke (Teks)
